name: Run Python Script

on: workflow_dispatch  # Manual event to trigger the workflow on demand

jobs:
  run_package:
    name: Run Python Package
    runs-on: ubuntu-latest  # You can choose other runners as per your requirements

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Set up the required Python version
        
    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

    - name: pip cache
      uses: actions/cache@v3
      id: py-pip-cache # use this to check for `cache-hit` ==> if: steps.py-pip-cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    #- name: Install dependencies
     # run: |
      #  python -m pip install --upgrade pip
       # python -m pip install -r requirements.txt
        #python -m pip install -r demoPython/requirements.txt

    - name: Run Python package
      run: |
        python main.py
        python demoPython/main.py
