name: Run Python Script

on:
  workflow_dispatch:  # Manual event to trigger the workflow on demand

jobs:
  run_package:
    name: Run Python Package
    runs-on: ubuntu-latest  # You can choose other runners as per your requirements

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Set up the required Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -r demoPython/requirements.txt

    - name: Run Python package
      run: |
        python main.py
        python demoPython/main.py
